# These are supported funding model platforms

github: [ danielraban ]
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ZRD3W47HQ3EMJ&source=url
patreon: danielraban
ko_fi: davealden